### ISSUE TITLE
Modularise config

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#1110]
**Currently config for eternum works like this:**

1. Setup Config based on some values in the EternumGlobal object and within the sdk
2. Import the global json and values within the sdk to the client to reflect the config that has been set

**We need to get to this point:**

1. SDK contains 'default' values for everything, no EternumGlobal values
2. Config can be setup by using these values or by passing a new EternumGlobal json file into the setup functions and importing into the client

**Tasks todo:**
- [ ] Remove EternumGlobal dependencies from the SDK config. EternumGlobal should exist to be passed into the config, not be baked into it.
- [ ] Allow passing of the EternumGlobal into the setup config which will adjust the default objects from the sdk
- [ ] Create a typed version of the Eternum Global config, to allow for nicer devex
- [ ] Import new EternumGlobal into the client

**Comment by aymericdelab** [comment]
linked to #1110
