### ISSUE TITLE
[contracts + Client] Upgrading Realm

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#1719]
**Upgrades**

Realms can only build on the immediate 6 hexs around the Castle to begin with. They must upgrade to expand the buildable area.

**There 3 levels**:
**Level 1 - ** low tier resource costs
**Level 2 - ** mid tier resources costs
**Level 3 - ** high tier resources costs

**TODO:**

- [ ] Restrict building according to the level at contract level
- [ ] Add level config setup function
- [ ] Update function to upgrade Realm
- [ ] Restrict building at client level
