### ISSUE TITLE
[landing] New onboarding/landing site

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#1880]
Due to the complexity of the onboarding process, we've decided to develop a new application encompassing:

- **User Season Pass Management and Trading**
- **Resource Bridge**
- **Seasonal Data Analysis** (including player statistics and current season details)

### Site Breakdown

**Dashboard Site**
- Manages Season passes and provides game statistics and player management tools.

**Game Site**
- Allows users to select and settle their Season passes. All management tasks are handled through the new app to maintain clarity.

#### Season Pass Page (Assigned to @RedBeardEth)

**Implementation Stages:**

1. **Season Pass Minting:**
   - Mint from the Realm NFT.
   - Add Lords to pass.
   - Transfer pass to other players.

2. **Trading of Season Passes:**
   - Utilize a screenshot liquidity pool.
   - Enable trading on the Marketplace.

**Tasks:**
- [ ] Integrate Season Pass NFT from Torii: The player wil have none until they mint them.
- [ ] Access Owned Realms: Players will just be able to click 'mint' and create a pass. They must be connected to their controller as the pass will mint to it.
- [ ] Enable Season pass minting (refer to Figma for design).
- [ ] Facilitate Season pass transfers.
- [ ] Allow charging up of Season pass with ERC20 Lords.
- [ ] Design phase (@ponderingdemocritus).

**Note:** All GraphQL queries should be handled using **tanstack Query**. We plan to encapsulate these queries into the SDK, so both the dashboard and the game can use them where needed. 

#### Data Pass Page

**Metrics to Track:**
- Total Players.
- Total Season Lords Pool.
- Leaderboard.
